import type { FloodReport, HelpRequest, ReliefCenter } from "./types";

export const demoFloodReports: FloodReport[] = [
  {
    id: "report-mg-road",
    roadName: "MG Road",
    district: "ernakulam",
    locationName: "Near Padma Junction",
    coordinates: { lat: 9.9782, lng: 76.2827 },
    severity: "waterlogged",
    waterLevelCm: 18,
    description: "Slow traffic, water covering both lanes after the evening rain.",
    createdBy: "Community desk",
    createdAt: "2026-08-01T03:10:00.000Z",
    confirmations: 8,
    flags: 0
  },
  {
    id: "report-aluva-bridge",
    roadName: "Aluva Periyar Bridge Approach",
    district: "ernakulam",
    locationName: "Bank junction side",
    coordinates: { lat: 10.1079, lng: 76.3561 },
    severity: "waist-deep",
    waterLevelCm: 92,
    description: "Approach road flooded. Rescue vehicles only.",
    createdBy: "Ward volunteer",
    createdAt: "2026-08-01T02:44:00.000Z",
    confirmations: 15,
    flags: 1
  },
  {
    id: "report-kakkanad",
    roadName: "Seaport-Airport Road",
    district: "ernakulam",
    locationName: "Kakkanad signal",
    coordinates: { lat: 10.0169, lng: 76.3437 },
    severity: "knee-deep",
    waterLevelCm: 46,
    description: "Cars moving slowly. Two-wheelers are turning back.",
    createdBy: "Traffic control",
    createdAt: "2026-08-01T01:58:00.000Z",
    confirmations: 11,
    flags: 0
  },
  {
    id: "report-kuttanad",
    roadName: "AC Road",
    district: "alappuzha",
    locationName: "Nedumudy stretch",
    coordinates: { lat: 9.4494, lng: 76.4152 },
    severity: "not-passable",
    waterLevelCm: 132,
    description: "Road closed by police. Boats being used for access.",
    createdBy: "Control room",
    createdAt: "2026-08-01T03:36:00.000Z",
    confirmations: 21,
    flags: 0
  },
  {
    id: "report-changanassery",
    roadName: "Changanassery Bypass",
    district: "kottayam",
    locationName: "Market road entry",
    coordinates: { lat: 9.4447, lng: 76.5365 },
    severity: "waterlogged",
    waterLevelCm: 22,
    description: "Water receding, buses moving carefully.",
    createdBy: "Bus stand desk",
    createdAt: "2026-08-01T02:25:00.000Z",
    confirmations: 6,
    flags: 1
  },
  {
    id: "report-thrissur",
    roadName: "Shornur Road",
    district: "thrissur",
    locationName: "Punkunnam side",
    coordinates: { lat: 10.535, lng: 76.199 },
    severity: "knee-deep",
    waterLevelCm: 54,
    description: "Traffic diverted toward Swaraj Round.",
    createdBy: "Local reporter",
    createdAt: "2026-08-01T01:18:00.000Z",
    confirmations: 7,
    flags: 0
  },
  {
    id: "report-kozhikode",
    roadName: "Mavoor Road",
    district: "kozhikode",
    locationName: "Medical college turn",
    coordinates: { lat: 11.2711, lng: 75.836 },
    severity: "waist-deep",
    waterLevelCm: 88,
    description: "Ambulances advised to use the bypass.",
    createdBy: "Hospital desk",
    createdAt: "2026-08-01T00:45:00.000Z",
    confirmations: 13,
    flags: 0
  }
];

export const demoHelpRequests: HelpRequest[] = [
  {
    id: "help-alangad",
    requesterName: "Nisha",
    contact: "+91 90000 01011",
    district: "ernakulam",
    locationName: "Alangad panchayat office road",
    coordinates: { lat: 10.1328, lng: 76.2996 },
    type: "rescue",
    priority: "critical",
    peopleCount: 5,
    description: "Two elderly people and a child need evacuation from the first floor.",
    status: "open",
    createdAt: "2026-08-01T03:42:00.000Z"
  },
  {
    id: "help-vyttila",
    requesterName: "Sajeev",
    contact: "+91 90000 02022",
    district: "ernakulam",
    locationName: "Vyttila mobility hub lane",
    coordinates: { lat: 9.9674, lng: 76.3186 },
    type: "medicine",
    priority: "high",
    peopleCount: 2,
    description: "Insulin and BP medicine required by evening.",
    status: "assigned",
    assignedVolunteer: "Team East-3",
    createdAt: "2026-08-01T02:18:00.000Z"
  },
  {
    id: "help-kuttanad-water",
    requesterName: "Joseph",
    contact: "+91 90000 03033",
    district: "alappuzha",
    locationName: "Pulinkunnu school lane",
    coordinates: { lat: 9.4191, lng: 76.4146 },
    type: "water",
    priority: "high",
    peopleCount: 18,
    description: "Drinking water needed for families staying on upper floor.",
    status: "in-progress",
    assignedVolunteer: "Boat unit A2",
    createdAt: "2026-08-01T01:50:00.000Z"
  },
  {
    id: "help-kozhikode-charge",
    requesterName: "Farha",
    contact: "+91 90000 04044",
    district: "kozhikode",
    locationName: "Near Medical College hostel",
    coordinates: { lat: 11.2726, lng: 75.8371 },
    type: "charging",
    priority: "medium",
    peopleCount: 9,
    description: "Phones and torch batteries need charging.",
    status: "open",
    createdAt: "2026-08-01T00:20:00.000Z"
  }
];

export const demoReliefCenters: ReliefCenter[] = [
  {
    id: "center-ernakulam-townhall",
    name: "Ernakulam Town Hall Camp",
    district: "ernakulam",
    type: "relief-camp",
    coordinates: { lat: 9.9844, lng: 76.2834 },
    address: "Town Hall Road, Kochi",
    contact: "0484 230 1000",
    capacity: 420,
    occupancy: 268,
    supplies: ["Meals", "Water", "Blankets", "Charging"]
  },
  {
    id: "center-general-hospital",
    name: "General Hospital Ernakulam",
    district: "ernakulam",
    type: "hospital",
    coordinates: { lat: 9.9786, lng: 76.2794 },
    address: "Hospital Road, Marine Drive",
    contact: "0484 238 6000",
    capacity: 180,
    occupancy: 142,
    supplies: ["Emergency care", "Medicine", "Ambulance"]
  },
  {
    id: "center-aluva-school",
    name: "Aluva GHSS Relief Camp",
    district: "ernakulam",
    type: "relief-camp",
    coordinates: { lat: 10.1068, lng: 76.3532 },
    address: "Palace Road, Aluva",
    contact: "0484 262 4000",
    capacity: 360,
    occupancy: 331,
    supplies: ["Meals", "Water", "Medical desk"]
  },
  {
    id: "center-kakkanad-fire",
    name: "Kakkanad Fire Station",
    district: "ernakulam",
    type: "fire-station",
    coordinates: { lat: 10.0151, lng: 76.3447 },
    address: "Civil Station Road, Kakkanad",
    contact: "101",
    capacity: 60,
    occupancy: 18,
    supplies: ["Rescue team", "Ropes", "Pumps"]
  },
  {
    id: "center-alappuzha-sdvc",
    name: "SDV School Camp",
    district: "alappuzha",
    type: "relief-camp",
    coordinates: { lat: 9.4931, lng: 76.3311 },
    address: "Zilla Court Ward, Alappuzha",
    contact: "0477 225 1720",
    capacity: 520,
    occupancy: 401,
    supplies: ["Meals", "Water", "Baby kits"]
  },
  {
    id: "center-kottayam-medical",
    name: "Kottayam Medical College",
    district: "kottayam",
    type: "hospital",
    coordinates: { lat: 9.632, lng: 76.5182 },
    address: "Gandhinagar, Kottayam",
    contact: "0481 259 7279",
    capacity: 260,
    occupancy: 198,
    supplies: ["Emergency care", "Ambulance", "Blood bank"]
  },
  {
    id: "center-kozhikode-camp",
    name: "Medical College HSS Camp",
    district: "kozhikode",
    type: "relief-camp",
    coordinates: { lat: 11.2719, lng: 75.8379 },
    address: "Medical College Road, Kozhikode",
    contact: "0495 235 6500",
    capacity: 470,
    occupancy: 355,
    supplies: ["Meals", "Water", "Medicine", "Charging"]
  }
];
